#!/bin/bash

set -e

# Update system and install necessary packages
sudo apt update 
sudo apt install -y python3 python3-pip python3-venv

# Install Docker using the official script
curl -fsSL https://get.docker.com -o get-docker.sh
echo "Installing Docker..."
sudo sh get-docker.sh 
echo "Docker installed successfully!"

echo "Adding user 'ubuntu' to Docker group..."
sudo usermod -aG docker ubuntu 
echo "User 'ubuntu' added to Docker group successfully!"

# Set up Python virtual environment and install LocalStack
echo "Setting up Python virtual environment and installing LocalStack..."
python3 -m venv /home/ubuntu/localstack-env
source /home/ubuntu/localstack-env/bin/activate
pip install awscli awscli-local localstack
